collections:
  - name: arista.avd
    version: "4.6.0"    # Confirmed stable
  - name: arista.cvp
    version: "3.6.0"    # Latest major
  - name: arista.eos
    version: "1.3.0"    # ✅ Use a valid, published version
