all:
  children:
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                clab-ceos-lab-ceos1:
                  ansible_host: 172.20.20.11
                  type: spine
                clab-ceos-lab-ceos2:
                  ansible_host: 172.20.20.12
                  type: spine
            DC1_LEAFS:
              hosts:
                clab-ceos-lab-leaf1a:
                  ansible_host: 172.20.20.21
                  type: l3leaf
                clab-ceos-lab-leaf1b:
                  ansible_host: 172.20.20.22
                  type: l3leaf

          vars:
            fabric_name: DC1_FABRIC

            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_user: admin
            ansible_password: admin
            ansible_become: true
            ansible_become_method: enable

            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false
            ansible_httpapi_port: 443

            # Management interface settings
            mgmt_interface: Management0
            mgmt_interface_vrf: default
            mgmt_gateway: 172.20.20.1

            # Required IP pools
            loopback_ipv4_pool: 192.168.255.0/24
            vtep_loopback_ipv4_pool: 192.168.254.0/24
            mlag_peer_ipv4_pool: 10.255.252.0/24
            mlag_peer_l3_ipv4_pool: 10.255.251.0/24

            # P2P settings
            p2p_uplinks_mtu: 1500

            # BGP peer group passwords
            bgp_peer_groups:
              ipv4_underlay_peers:
                password: "AQQvKeimxJu+uGQ/yYvv9w=="
              evpn_overlay_peers:
                password: "q+VNViP5i4rVjW1cxFv2wA=="
              mlag_ipv4_underlay_peer:
                password: "vnEaG8gMeQf3d3cN6PktXQ=="

            # Spine definition
            spine:
              defaults:
                platform: cEOS
                bgp_as: 65001
                loopback_ipv4_pool: 192.168.255.0/24
              nodes:
                - name: clab-ceos-lab-ceos1
                  id: 1
                  mgmt_ip: 172.20.20.11/24
                - name: clab-ceos-lab-ceos2
                  id: 2
                  mgmt_ip: 172.20.20.12/24

            # Leaf definition
            l3leaf:
              defaults:
                platform: cEOS
                loopback_ipv4_pool: 192.168.255.0/24
                vtep_loopback_ipv4_pool: 192.168.254.0/24
                mlag_interfaces: [Ethernet3, Ethernet4]
                virtual_router_mac_address: 00:1c:73:00:dc:01
                uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
                spines: [clab-ceos-lab-ceos1, clab-ceos-lab-ceos2]
              node_groups:
                - group: DC1_LEAF1
                  bgp_as: 65101
                  nodes:
                    - name: clab-ceos-lab-leaf1a
                      id: 1
                      mgmt_ip: 172.20.20.21/24
                      uplink_switches: [clab-ceos-lab-ceos1, clab-ceos-lab-ceos2]
                      uplink_interfaces: [Ethernet1, Ethernet2]
                      mlag_peer_ip: 10.255.252.1
                      mlag_peer_l3_ip: 10.255.251.1
                    - name: clab-ceos-lab-leaf1b
                      id: 2
                      mgmt_ip: 172.20.20.22/24
                      uplink_switches: [clab-ceos-lab-ceos1, clab-ceos-lab-ceos2]
                      uplink_interfaces: [Ethernet1, Ethernet2]
                      mlag_peer_ip: 10.255.252.2
                      mlag_peer_l3_ip: 10.255.251.2

            # BGP defaults
            spine_bgp_defaults:
              - no bgp default ipv4-unicast
              - distance bgp 20 200 200
              - graceful-restart restart-time 300
              - graceful-restart

            leaf_bgp_defaults:
              - no bgp default ipv4-unicast
              - distance bgp 20 200 200
              - graceful-restart restart-time 300
              - graceful-restart
