all:
  children:
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                clab-ceos-lab-ceos1:
                  ansible_host: 172.20.20.11
                  type: spine
                clab-ceos-lab-ceos2:
                  ansible_host: 172.20.20.12
                  type: spine
            DC1_LEAFS:
              hosts:
                clab-ceos-lab-leaf1a:
                  ansible_host: 172.20.20.21
                  type: l3leaf
                clab-ceos-lab-leaf1b:
                  ansible_host: 172.20.20.22
                  type: l3leaf
              vars:  # <-- move IP pools HERE
                mlag_peer_ipv4_pool: 10.255.252.0/24
                mlag_peer_l3_ipv4_pool: 10.255.251.0/24
                loopback_ipv4_pool: 192.168.255.0/24
                vtep_loopback_ipv4_pool: 192.168.254.0/24
