---
all:
  children:
    DC1:
      children:
        DC1_FABRIC:
          children:
            DC1_SPINES:
              hosts:
                clab-ceos-lab-ceos1:
                  ansible_host: 172.20.20.11
                clab-ceos-lab-ceos2:
                  ansible_host: 172.20.20.12
          vars:
            ansible_connection: httpapi
            ansible_network_os: eos
            ansible_become: true
            ansible_become_method: enable
            ansible_user: admin      # REQUIRED
            ansible_password: admin    # REQUIRED
            ansible_httpapi_use_ssl: true
            ansible_httpapi_validate_certs: false
            ansible_httpapi_port: 443
            evpn_services_l2_only: false
            evpn_services_l3_only: false
            evpn_vlan_aware_bundles: true  # Updated variable name
            vxlan_vlan_aware_bundles: null  # Explicitly remove deprecated variable
