---
# Main AVD Playbook Without CVP

- name: Debug host vars
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  tasks:
    - name: Dump host vars for troubleshooting
      debug:
        var: hostvars[inventory_hostname]

- name: Manage Arista EOS EVPN/VXLAN Configuration (No CVP)
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Reset local folders for output
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders

    - name: Generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: Generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Deploy configuration to devices via eAPI
      tags: [deploy]
      import_role:
        name: arista.avd.eos_config_deploy_eapi
