- name: Manage Arista EOS EVPN/VXLAN Configuration (No CVP)
  hosts: DC1_FABRIC
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:

    - name: Reset local folders for output
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders

    - name: 🔍 DEBUG — Dump all host variables before eos_designs
      debug:
        var: hostvars[inventory_hostname]

    - name: Generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: Generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_cli_config_gen

    - name: Deploy configuration to devices via eAPI
      tags: [deploy]
      import_role:
        name: arista.avd.eos_config_deploy_eapi

    # New: Slurp generated CLI config and expose via AWX
    - name: Read rendered config from /tmp/intended/configs
      slurp:
        src: "/tmp/intended/configs/{{ inventory_hostname }}.cfg"
      register: rendered_config
      delegate_to: localhost
      run_once: false

    - name: Show rendered config in AWX UI
      debug:
        msg: "{{ rendered_config['content'] | b64decode }}"
      delegate_to: localhost
      run_once: false

    - name: Store config output for AWX job artifact
      set_stats:
        data:
          "{{ inventory_hostname }}_config": "{{ rendered_config['content'] | b64decode }}"
      delegate_to: localhost
      run_once: false
