---
root_dir: '/tmp/'
inventory_file: '{{root_dir}}/inventory.yml'
evpn_vlan_aware_bundles: true
avd_ignore_requirements: true  # Temporarily add this to bypass validation

ansible_connection: httpapi
ansible_network_os: eos
ansible_user: admin
ansible_password: admin
ansible_become: true
ansible_become_method: enable

ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 443

# Local users
local_users:
  admin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Df86J4/SFMDE3/1K$Hef4KstdoxNDaami37cBquTWOTplC.miMPjXVgQxMe92.e5wxlnXOLlebgPj8Fz1KO0za/RCO7ZIs4Q6Eiq1g1"

  cvpadmin:
    privilege: 15
    role: network-admin
    sha512_password: "$6$rZKcbIZ7iWGAWTUM$TCgDn1KcavS0s.OV8lacMTUkxTByfzcGlFlYUWroxYuU7M/9bIodhRO7nXGzMweUxvbk8mJmQl8Bh44cRktUj."

  ansible:
    privilege: 15
    role: network-admin
    sha512_password: "$6$Dzu11L7yp9j3nCM9$FSptxMPyIL555OMO.ldnjDXgwZmrfMYwHSr0uznE5Qoqvd9a6UdjiFcJUhGLtvXVZR1r.A/iF5aAt50hf/EK4/"

# Management gateway
mgmt_gateway: 10.255.0.1

# DNS servers
name_servers:
  - 192.168.2.1
  - 8.8.8.8

# NTP servers
ntp_servers:
  - 0.fr.pool.ntp.org
  - 1.fr.pool.ntp.org
