---
# L3LS Fabric Values - Updated for containerlab topology

fabric_name: DC1_FABRIC

underlay_p2p_network_summary: 172.31.255.0/24
overlay_loopback_network_summary: 192.168.255.0/24
vtep_loopback_network_summary: 192.168.254.0/24

mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

bgp_peer_groups:
  ipv4_underlay_peers:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  evpn_overlay_peers:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  mlag_ipv4_underlay_peer:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

mgmt_interface: Management0
mgmt_interface_vrf: default
mgmt_gateway: 172.20.20.1

spine:
  platform: cEOS
  bgp_as: 65001
  leaf_as_allocation_range: 65101-65132
  nodes:
    clab-ceos-lab-ceos1:
      id: 1
      mgmt_ip: 172.20.20.11/24
    clab-ceos-lab-ceos2:
      id: 2
      mgmt_ip: 172.20.20.12/24

l3leaf:
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: cEOS
    spines: [clab-ceos-lab-ceos1, clab-ceos-lab-ceos2]
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        clab-ceos-lab-leaf1a:
          id: 1
          mgmt_ip: 172.20.20.21/24
          spine_interfaces: [Ethernet1, Ethernet2]
        clab-ceos-lab-leaf1b:
          id: 2
          mgmt_ip: 172.20.20.22/24
          spine_interfaces: [Ethernet1, Ethernet2]

spine_bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

p2p_uplinks_mtu: 1500

bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

platform_settings:
  - platforms: [cEOS]
    reload_delay:
      mlag: 300
      non_mlag: 330
    feature_support:
      queue_monitor_length: false
      interface_storm_control: false

# Optional CVP configlets
# cv_configlets:
#   containers:
#     DC1_L3LEAFS:
#       - ASE_GLOBAL-ALIASES
