spine:
  type: spine  # ✅ Required by AVD
  defaults:
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.255.0/24
  platform: cEOS
  leaf_as_allocation_range: 65101-65132
  nodes:
    clab-ceos-lab-ceos1:
      id: 1
      mgmt_ip: 172.20.20.11/24
    clab-ceos-lab-ceos2:
      id: 2
      mgmt_ip: 172.20.20.12/24

l3leaf:
  type: l3leaf  # ✅ Required by AVD
  defaults:
    virtual_router_mac_address: 00:1c:73:00:dc:01
    platform: cEOS
    spines: [clab-ceos-lab-ceos1, clab-ceos-lab-ceos2]
    uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
    mlag_interfaces: [Ethernet3, Ethernet4]
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.254.0/24
  node_groups:
    DC1_LEAF1:
      bgp_as: 65101
      nodes:
        clab-ceos-lab-leaf1a:
          id: 1
          mgmt_ip: 172.20.20.21/24
          spine_interfaces: [Ethernet1, Ethernet2]
        clab-ceos-lab-leaf1b:
          id: 2
          mgmt_ip: 172.20.20.22/24
          spine_interfaces: [Ethernet1, Ethernet2]
