---
# L3LS Fabric Values - Updated for containerlab topology
# SOME CHANGES COULD BE DISRUPTIVE.

fabric_name: DC1_FABRIC

# Point to Point Network Summary range, assigned as /31 for each
# uplink interfaces
# Assign range larger then total [spines * total potential leafs * 2]
underlay_p2p_network_summary: 172.31.255.0/24

# IP address range for evpn loopback for all switches in fabric,
# assigned as /32s
# Assign range larger then total spines + total leafs switches
overlay_loopback_network_summary: 192.168.255.0/24

# VTEP VXLAN Tunnel source loopback IP for leaf switches, assigned in /32s
# Assign range larger then total leaf switches
vtep_loopback_network_summary: 192.168.254.0/24

# mlag pair IP assignment - assign blocks - Assign range larger then
# total spines + total leafs switches
mlag_ips:
  leaf_peer_l3: 10.255.251.0/24
  mlag_peer: 10.255.252.0/24

# Enable vlan aware bundles
vxlan_vlan_aware_bundles: true

# bgp peer groups passwords
bgp_peer_groups:
  IPv4_UNDERLAY_PEERS:
    password: "AQQvKeimxJu+uGQ/yYvv9w=="
  EVPN_OVERLAY_PEERS:
    password: "q+VNViP5i4rVjW1cxFv2wA=="
  MLAG_IPv4_UNDERLAY_PEER:
    password: "vnEaG8gMeQf3d3cN6PktXQ=="

# Management interface settings
mgmt_interface: Management0
mgmt_interface_vrf: default
mgmt_gateway: 172.20.20.1

# Spine Switches - Updated for containerlab
spine:
  platform: cEOS
  bgp_as: 65001
  # defines the range of acceptable remote ASNs from leaf switches
  leaf_as_range: 65101-65132
  nodes:
    clab-ceos-lab-ceos1:
      id: 1
      mgmt_ip: 172.20.20.11/24
    clab-ceos-lab-ceos2:
      id: 2
      mgmt_ip: 172.20.20.12/24

# Since you only have spines in containerlab, commenting out leaf configuration
# Uncomment and modify when you add leaf switches to your topology

# l3leaf:
#   defaults:
#     # virtual router mac for VNIs assigned to Leaf switches
#     # format: xx:xx:xx:xx:xx:xx
#     virtual_router_mac_address: 00:1c:73:00:dc:01
#     platform: cEOS
#     bgp_as: 65100
#     spines: [clab-ceos-lab-ceos1, clab-ceos-lab-ceos2]
#     uplink_to_spine_interfaces: [Ethernet1, Ethernet2]
#     mlag_interfaces: [Ethernet3, Ethernet4]
#     spanning_tree_priority: 4096
#     spanning_tree_mode: mstp
#   node_groups:
#     DC1_LEAF1:
#       bgp_as: 65101
#       nodes:
#         clab-ceos-lab-leaf1a:
#           id: 1
#           mgmt_ip: 172.20.20.21/24
#           spine_interfaces: [Ethernet1, Ethernet1]
#         clab-ceos-lab-leaf1b:
#           id: 2
#           mgmt_ip: 172.20.20.22/24
#           spine_interfaces: [Ethernet2, Ethernet2]

# l2leaf: (commented out - not needed for spine-only topology)

#### Override for cEOS Lab Caveats ####

# Disable update wait-for-convergence and update wait-for-install,
# which is not supported in cEOS-LAB.
# Refer to design guide

spine_bgp_defaults:
  #  - update wait-for-convergence
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

leaf_bgp_defaults:
  #  - update wait-install
  - no bgp default ipv4-unicast
  - distance bgp 20 200 200
  - graceful-restart restart-time 300
  - graceful-restart

# Update p2p mtu 9000 -> 1500 (suitable for containerlab)
p2p_uplinks_mtu: 1500

# Adjust default bfd values
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3

# Platform specific settings for cEOS
platform_settings:
  - platforms: [cEOS]
    reload_delay:
      mlag: 300
      non_mlag: 330
    feature_support:
      queue_monitor_length: false
      interface_storm_control: false

# List of additional CVP configlets to bind to devices and containers
# Configlets MUST be configured on CVP before running AVD playbooks.

# cv_configlets:
#   containers:
#     DC1_L3LEAFS:
#       - ASE_GLOBAL-ALIASES
